# config/packages/twig.yaml
twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/public/assets/img': images
        '%kernel.project_dir%/public/assets/css': css

